---
title: "AO19 - Nadal/Djoker Animation"
author: "Adil Alimohd"
date: "March 22, 2020"
output: html_document
---

```{r library & data load, include=FALSE}

library(tidyverse)
library(ggplot2)
library(gganimate)
library(dplyr)
library(knitr)
library(reshape2)
library(readr)

setwd("C:/Users/U385722/OneDrive - Health Care Service Corporation/Desktop/Misc/Data Science\Datasets & Projects/Australian Open 2019")

rally = read.csv("rallies.csv")
serve = read.csv("serves.csv")
point = read.csv("points.csv")
event = read.csv("events.csv")

```

```{r view data, include=FALSE}

head(rally)
head(serve)
head(point)
head(event)

```

```{r creating the court base, include=FALSE}

out_bounds <- data.frame(
    x = c(0, 0, 23.77, 23.77, 0),
    y = c(0, 10.97, 10.97, 0, 0)
)

t_lines <- data.frame(
    x = c(5.585, 5.585, 5.585, 18.385, 18.385, 18.385),
    y = c(1.37, 9.6, 5.485, 5.485, 1.37, 9.6)
)

court <- ggplot() +
    geom_path(data = out_bounds, aes(x = x, y = y)) +
    geom_path(data = t_lines, aes(x = x, y = y)) +
    geom_path(aes(x = c(23.77, 0), y = c(1.37, 1.37))) + # lower singles lines
    geom_path(aes(x = c(23.77, 0), y = c(9.6, 9.6))) + # upper singles lines
    geom_path(aes(x = c(11.985, 11.985), y = c(0, 10.97)), lty = 2) + # net line
    ylim(c(-1, 11.97)) + xlim(c(-4, 27.77)) + 
    theme_void()

court

```

```{r flipping x/y coordinates in raw data, include=FALSE}

event <- event %>% 
    rename(hitter_x = hitter_y,
           hitter_y = hitter_x,
           receiver_x = receiver_y,
           receiver_y = receiver_x)

point <- point %>% 
    rename(x = y,
           y = x)

serve <- serve %>% 
    rename(y = x,
           x = y)

```


```{r hitter positions, include=FALSE}

court +
    geom_point(data = event,
             aes(x = hitter_x, y = hitter_y, colour = hitter)
             ) +
    theme(legend.position = "bottom", 
          plot.title = element_text(hjust = 0.5)) +
    ggtitle("Position Of Hitters")

```

```{r winners, include=FALSE}

tmp <- point %>% 
    filter(reason == "winner")

court +
    geom_point(data = tmp, aes(x = x, y = y, colour = winner)) +
    theme(legend.position = "bottom",
          plot.title = element_text(hjust = 0.5)) + 
    ggtitle("Winner Positions")

```

```{r data manipulation & melting, include=FALSE}

tmp <- event %>% 
    filter(isserve == 'True') %>% 
    select(rallyid, receiver, hitter_x, hitter_y, receiver_x, receiver_y) %>% 
    right_join(serve, by = "rallyid")



 # The next two assignments take care of only including serves with a return
sec_stroke <- event %>% 
    filter(strokeid == 2) %>% 
    rename(return_x = hitter_x, return_y = hitter_y) %>% 
    select(rallyid, return_y, return_x)

tmp <-  tmp %>% inner_join(sec_stroke, by = "rallyid") %>% 
    mutate(
        receiver_x = return_x,
        receiver_y = return_y
    ) %>% 
    select(-return_y, -return_x)

 # We start melting the frames to create coordinate matrices for each rally
tmp_mx <- tmp %>%
    rename(hitter = hitter_x,
           coord = x,
           receive = receiver_x) %>% 
    melt(id.vars = c("rallyid", "server", "receiver"),
         measure.vars = c("hitter", "coord", "receive")
    ) %>% 
    rename(x_kind = variable,
           x = value)

tmp_my <- tmp %>%
    rename(hitter = hitter_y,
           coord = y,
           receive = receiver_y) %>% 
    melt(id.vars = c("rallyid", "server", "receiver"),
         measure.vars = c("hitter", "coord", "receive")
    ) %>% 
    rename(y_kind = variable,
           y = value)

df <- inner_join(tmp_mx, tmp_my[, c("rallyid", "y_kind", "y")], by = c("rallyid", "x_kind" = "y_kind"))

head(df)

```

```{r}

serve_p <- court +
    geom_path(data = df, aes(x = x, y = y, group = rallyid, color = server)) +
    theme(legend.position = "bottom",
          plot.title = element_text(hjust = 0.5)) +
    ggtitle("Serve Direction")

serve_p+  geom_point(data = df, aes(x = x, y = y, group = rallyid, color = server))

```

```{r creating ball position & 3x2 matrix for animate, include=FALSE}

ball_x <- event %>%
    melt(id.vars = c("rallyid", "strokeid", "hitter", "receiver"),
         measure.vars = c("hitter_x")
    ) %>% 
    rename(x_kind = variable,
           x = value)
ball_y <- event %>% 
    melt(id.vars = c("rallyid", "strokeid", "hitter", "receiver"),
         measure.vars = c("hitter_y")
    ) %>% 
    rename(y_kind = variable,
           y = value)

ball_pos <- inner_join(ball_x, ball_y[, c("rallyid", "strokeid", "y")], by = c("rallyid", "strokeid"))

kable(head(arrange(ball_pos, rallyid)))

```



```{r}

court_b <- ggplot() +
    geom_path(data = out_bounds, aes(x = x, y = y), colour = "white", size = 1.5, lineend = "square") +
    geom_path(data = t_lines, aes(x = x, y = y), colour = "white", size = 1.5, lineend = "square") +
    geom_path(aes(x = c(23.77, 0), y = c(1.37, 1.37)), colour = "white", size = 1.5, lineend = "square") + # lower singles lines
    geom_path(aes(x = c(23.77, 0), y = c(9.6, 9.6)), colour = "white", size = 1.5, lineend = "square") + # upper singles lines
    geom_path(aes(x = c(11.985, 11.985), y = c(0, 10.97)), lty = 1, colour = "white", size = 1.5, lineend = "square") + # net line
    ylim(c(-1, 11.97)) + xlim(c(-4, 27.77)) + 
    theme_void() +
    theme(
        plot.background = element_rect("#5080B0")
    )
court_b

```

```{r}

court_b +
    geom_point(data = ball_pos, aes(x = x, y = y), colour = "yellow")

```

```{r}

kable(head(arrange(rally, desc(strokes))))


```

```{r}
library(grid)
library(gridExtra)

ani_df <- ball_pos %>% 
    filter(rallyid == 206) 

rally_points <- court_b + 
    geom_point(data = ani_df, aes(x = x, y = y), colour = "yellow")

rally_lines <- court_b + 
    geom_point(data = ani_df, aes(x = x, y = y), colour = "yellow") +
    geom_path(data = ani_df, aes(x = x, y = y), colour = "yellow")
 


grid.arrange(rally_points, rally_lines, nrow = 2)

```

```{r}

gif_lines <- rally_lines +     
    transition_reveal(strokeid)

gif_lines
```

```{r}

gif_ball <- court_b + 
    geom_point(data = ani_df, aes(x = x, y = y), colour = "yellow") +
    geom_path(data = ani_df, aes(x = x, y = y), colour = NA) +     
    transition_reveal(strokeid)

#animate(gif_ball, nframes = 200)

gif_ball
```

```{r}

# First, create new variables for the positions
base <- ball_pos %>% 
    mutate(
        nadal_x = ifelse(hitter == "Nadal", x, NA),
        nadal_y = ifelse(hitter == "Nadal", y, NA),
        djo_x = ifelse(hitter == "Djokovic", x, NA),
        djo_y = ifelse(hitter == "Djokovic", y, NA)
        )

# Fill the new variables with starting positions for the return player
base <- base %>% 
    left_join(event[c("rallyid", "strokeid", "receiver_x", "receiver_y")], by = c("rallyid", "strokeid")) %>% 
    mutate(
        nadal_x = ifelse((strokeid == 1 & receiver == "Nadal"), receiver_x, nadal_x),
        nadal_y = ifelse(strokeid == 1 & receiver == "Nadal", receiver_y, nadal_y),
        djo_x = ifelse(strokeid == 1 & receiver == "Djokovic", receiver_x, djo_x),
        djo_y = ifelse(strokeid == 1 & receiver == "Djokovic", receiver_y, djo_y)
    ) %>% 
    select(-receiver_x, -receiver_y)


# Fill the new variables with the end positions of a rally
base <- base %>% 
    group_by(rallyid) %>% 
    mutate(
        nadal_x = ifelse(strokeid == max(strokeid) & strokeid != 1 & receiver == "Nadal",
                         nadal_x[strokeid == max(strokeid) - 1], 
                         nadal_x),
        nadal_y = ifelse(strokeid == max(strokeid) & strokeid != 1 & receiver == "Nadal", 
                         nadal_y[strokeid == max(strokeid) - 1], 
                         nadal_y),
        djo_x = ifelse(strokeid == max(strokeid) & strokeid != 1 & receiver == "Djokovic", 
                       djo_x[strokeid == max(strokeid) - 1], 
                       djo_x),
        djo_y = ifelse(strokeid == max(strokeid) & strokeid != 1 & receiver == "Djokovic", 
                       djo_y[strokeid == max(strokeid) - 1],
                       djo_y),
    )

# Interpolate between the respective hits
base <- base %>% 
    group_by(rallyid) %>% 
    mutate(
        nadal_x = ifelse(is.na(nadal_x), (lag(nadal_x) + lead(nadal_x))/2, nadal_x),
        nadal_y = ifelse(is.na(nadal_y), (lag(nadal_y) + lead(nadal_y))/2, nadal_y),
        djo_x = ifelse(is.na(djo_x), (lag(djo_x) + lead(djo_x))/2, djo_x),
        djo_y = ifelse(is.na(djo_y), (lag(djo_y) + lead(djo_y))/2, djo_y)
    )

base <- base %>% 
    left_join(point[, c("rallyid", "score")], by = "rallyid") %>% 
    filter(!is.na("score"))

base

```


```{r}

ani_df <- base %>% filter(rallyid == 206)

gif_replay <- court_b + 
    # ball
    geom_point(data = ani_df, aes(x = x, y = y), colour = "yellow", size = 3) +
    geom_path(data = ani_df, aes(x = x, y = y), colour = NA) +     
    # nadal
    geom_point(data = ani_df, aes(x = nadal_x, y = nadal_y), size = 8, col = "orange") + 
    geom_text(data = ani_df, aes(x = nadal_x, y = nadal_y, label = "N")) +
    # djokovic
    geom_point(data = ani_df, aes(x = djo_x, y = djo_y), size = 8, col = "white") +
    geom_text(data = ani_df, aes(x = djo_x, y = djo_y, label = "D")) +
    transition_reveal(strokeid)

#animate(gif_replay, nframes = 200, width = 800)



```


```{r}

score <- ani_df[1, "score"]
serve <- ani_df[1, "hitter"]

gif_hud <- court_b +
    ylim(c(-1, 14)) +
    geom_text(aes(x = 2, y = 13.5, label = paste0("Score: ", score)), color = "white") +
    geom_text(aes(x = 2, y = 12.5, label = paste0("Serve: ", serve)), color = "white") +
    #geom_text(data = ani_df, aes(x = 6, y = 13.5, label = round(strokenum)), color = "white") +
     # ball
    geom_point(data = ani_df, aes(x = x, y = y), colour = "yellow", size = 3) +
    geom_path(data = ani_df, aes(x = x, y = y), colour = NA) +     
    # nadal
    geom_point(data = ani_df, aes(x = nadal_x, y = nadal_y), size = 8, col = "orange") + 
    geom_text(data = ani_df, aes(x = nadal_x, y = nadal_y, label = "N")) +
    # djokovic
    geom_point(data = ani_df, aes(x = djo_x, y = djo_y), size = 8, col = "white") +
    geom_text(data = ani_df, aes(x = djo_x, y = djo_y, label = "D")) +
    transition_reveal(strokeid)

animate(gif_hud, nframes = 40, width = 800)    


```

